
Parameters:
  EnvirName:
    Description: An environment name that is prefixed to resource names
    Type: String
Resources:
  NewVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.0.0/16"
      Tags:
        - Key: Name
          Value: !Ref EnvirName
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-west-2a" 
      VpcId: !Ref NewVPC
      CidrBlock: "192.168.1.0/24"
      MapPublicIpOnLaunch: true
  
  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-west-2b" 
      VpcId: !Ref NewVPC
      CidrBlock: "192.168.2.0/24"
      MapPublicIpOnLaunch: false
  
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH Protocol and HTTP access"
      VpcId: !Ref NewVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-00b44d3dbe1f81742"
      InstanceType: "t2.micro"
      KeyName: "ahmed-key"
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup